name: recommenderApiWecloud
channels:
- conda-forge
- defaults
dependencies:
- certifi=2016.2.28=py35_0
- psycopg2=2.6.1=py35_1
- python=3.5.4=0
- readline=6.2=2
- setuptools=36.4.0=py35_1
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py35_0
- xz=5.2.3=0
- zlib=1.2.11=0
- astroid==1.5.3
- bcrypt==3.1.0
- blinker==1.4
- cffi==1.7.0
- click==6.6
- cov-core==1.15.0
- coverage==4.2
- cycler==0.10.0
- flask==0.11.1
- flask-bcrypt==0.7.1
- flask-httpauth==3.2.1
#- flask-jwt>=0.3.2
- flask-login==0.3.2
- flask-mail==0.9.1
#- flask-migrate==2.0.0
#- flask-pagedown==0.2.1
- flask-restful==0.3.6
- flask-restplus==0.9.2
- flask-script==2.0.5
- flask-sqlalchemy==2.1
- flask-uploads==0.2.1
- flask-wtf==0.12
#- freeze==1.0.10
- gunicorn==19.6.0
- html5lib==0.9999999
- httplib2==0.10.3
- isort==4.2.15
- itsdangerous==0.24
- jinja2==2.8
- jsonschema==2.6.0
- lazy-object-proxy==1.3.1
- mako==1.0.4
- markdown==2.6.7
- markupsafe==0.23
- matplotlib==2.1.0
- mccabe==0.6.1
#- nose2==0.6.4
- numpy==1.13.3
- pandas==0.21.0
- pycparser==2.14
- pygments==2.1.3
- pyjwt==1.4.2
#- pylint==1.7.4
- pyparsing==2.2.0
- pysocks==1.6.6
- python-dateutil==2.6.1
- python-editor==1.0.1
- pytz==2016.10
- requests==2.11.1
- requests-toolbelt==0.7.0
- scikit-learn==0.19.1
- scipy==1.0.0
- six==1.10.0
- sqlalchemy==1.0.13
#- tkreadonly==0.6.0
#- twilio==5.7.0
- werkzeug==0.11.10
- wrapt==1.10.11
- wtforms==2.1
